In [ ]:
import sklearn
print(sklearn.__version__)


1.6.1


In [ ]:
!pip install pandas


  Using cached pandas-2.2.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Using cached pandas-2.2.3-cp313-cp313-win_amd64.whl (11.5 MB)


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report



In [ ]:
dt = pd.read_csv('heartdata.CSV')
dt.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   70    1   4       130   322    0        2      109      0      2.4      2   
1   67    0   3       115   564    0        2      160      0      1.6      2   
2   57    1   2       124   261    0        0      141      0      0.3      1   
3   64    1   4       128   263    0        0      105      1      0.2      2   
4   74    0   2       120   269    0        2      121      1      0.2      1   

   target  
0       2  
1       1  
2       2  
3       1  
4       1

In [ ]:
dt.shape

(270, 12)

In [ ]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       270 non-null    int64  
 1   sex       270 non-null    int64  
 2   cp        270 non-null    int64  
 3   trestbps  270 non-null    int64  
 4   chol      270 non-null    int64  
 5   fbs       270 non-null    int64  
 6   restecg   270 non-null    int64  
 7   thalach   270 non-null    int64  
 8   exang     270 non-null    int64  
 9   oldpeak   270 non-null    float64
 10  slope     270 non-null    int64  
 11  target    270 non-null    int64  
dtypes: float64(1), int64(11)
memory usage: 25.4 KB


In [ ]:
dt.describe()

age         sex          cp    trestbps        chol         fbs  \
count  270.000000  270.000000  270.000000  270.000000  270.000000  270.000000   
mean    54.433333    0.677778    3.174074  131.344444  249.659259    0.148148   
std      9.109067    0.468195    0.950090   17.861608   51.686237    0.355906   
min     29.000000    0.000000    1.000000   94.000000  126.000000    0.000000   
25%     48.000000    0.000000    3.000000  120.000000  213.000000    0.000000   
50%     55.000000    1.000000    3.000000  130.000000  245.000000    0.000000   
75%     61.000000    1.000000    4.000000  140.000000  280.000000    0.000000   
max     77.000000    1.000000    4.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang    oldpeak       slope      target  
count  270.000000  270.000000  270.000000  270.00000  270.000000  270.000000  
mean     1.022222  149.677778    0.329630    1.05000    1.585185    1.444444  
std      0.997891   23.165717    0.470952    1.14521    0.614390    0.497827  
min      0.000000   71.000000    0.000000    0.00000    1.000000    1.000000  
25%      0.000000  133.000000    0.000000    0.00000    1.000000    1.000000  
50%      2.000000  153.500000    0.000000    0.80000    2.000000    1.000000  
75%      2.000000  166.000000    1.000000    1.60000    2.000000    2.000000  
max      2.000000  202.000000    1.000000    6.20000    3.000000    2.000000

In [ ]:
dt.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
target      0
dtype: int64

In [ ]:
dt['target'].value_counts()

target
1    150
2    120
Name: count, dtype: int64

In [ ]:
# Define features and target
X = dt.drop('target', axis=1)  # Features
y = dt['target']  # Target

In [ ]:
# Split into train/test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()

# Fit and transform on training data, transform on test data
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [ ]:
# Step 6: Initialize and train the model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
logreg_model = LogisticRegression(max_iter=100, random_state=42)
svc_model = SVC(random_state=42)
gb_model = GradientBoostingClassifier(n_estimators=100, random_state=42)


In [ ]:
# Train each model
rf_model.fit(X_train, y_train)
logreg_model.fit(X_train, y_train)
svc_model.fit(X_train, y_train)
gb_model.fit(X_train, y_train)

GradientBoostingClassifier(random_state=42)

In [ ]:
# Predictions from each model
rf_pred = rf_model.predict(X_test)
logreg_pred = logreg_model.predict(X_test)
svc_pred = svc_model.predict(X_test)
gb_pred = gb_model.predict(X_test)

In [ ]:
# Evaluate individual models using accuracy score
print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))
print("Logistic Regression Accuracy:", accuracy_score(y_test, logreg_pred))
print("SVC Accuracy:", accuracy_score(y_test, svc_pred))
print("Gradient Boosting Accuracy:", accuracy_score(y_test, gb_pred))

Random Forest Accuracy: 0.7222222222222222
Logistic Regression Accuracy: 0.7407407407407407
SVC Accuracy: 0.8333333333333334
Gradient Boosting Accuracy: 0.7407407407407407


In [ ]:
# Classification Reports for each model
print("\nRandom Forest Classification Report:")
print(classification_report(y_test, rf_pred))

print("\nLogistic Regression Classification Report:")
print(classification_report(y_test, logreg_pred))

print("\nSVC Classification Report:")
print(classification_report(y_test, svc_pred))

print("\nGradient Boosting Classification Report:")
print(classification_report(y_test, gb_pred))


Random Forest Classification Report:
              precision    recall  f1-score   support

           1       0.74      0.85      0.79        33
           2       0.69      0.52      0.59        21

    accuracy                           0.72        54
   macro avg       0.71      0.69      0.69        54
weighted avg       0.72      0.72      0.71        54


Logistic Regression Classification Report:
              precision    recall  f1-score   support

           1       0.76      0.85      0.80        33
           2       0.71      0.57      0.63        21

    accuracy                           0.74        54
   macro avg       0.73      0.71      0.72        54
weighted avg       0.74      0.74      0.73        54


SVC Classification Report:
              precision    recall  f1-score   support

           1       0.83      0.91      0.87        33
           2       0.83      0.71      0.77        21

    accuracy                           0.83        54
   macro avg      

In [ ]:
# Confusion Matrices for each model
print("\nRandom Forest Confusion Matrix:")
print(confusion_matrix(y_test, rf_pred))

print("\nLogistic Regression Confusion Matrix:")
print(confusion_matrix(y_test, logreg_pred))

print("\nSVC Confusion Matrix:")
print(confusion_matrix(y_test, svc_pred))

print("\nGradient Boosting Confusion Matrix:")
print(confusion_matrix(y_test, gb_pred))


Random Forest Confusion Matrix:
[[28  5]
 [10 11]]

Logistic Regression Confusion Matrix:
[[28  5]
 [ 9 12]]

SVC Confusion Matrix:
[[30  3]
 [ 6 15]]

Gradient Boosting Confusion Matrix:
[[28  5]
 [ 9 12]]


In [ ]:
model = SVC()

In [ ]:
model.fit(X_train, y_train)

SVC()

In [ ]:
# Save the model using joblib
# Save both model and scaler
import joblib
joblib.dump(model, 'svc_model.joblib')


['svc_model.joblib']

In [ ]:
# To load the model later
loaded_model = joblib.load('svc_model.joblib')